### ISSUE TITLE
A suggestion to use #!/usr/bin/env python instead of #!/usr/bin/python

### ISSUE THREAD

**Issue by mingzhi** [snayfach/PhyloCNV#3]
It is better to use #!/usr/bin/env python than #!/usr/bin/python, which can give user maximum flexibility to choose the interpreter to use. For example, in our HPC, there exists several versions of python and the default version (/usr/bin/python) is quite old. By loading other versions of python, we can not simply run run_phylo_cnv.py (after appending it to the PATH), but need to run "python scripts_dir/run_phylo_cnv.py".

**Comment by snayfach** [comment]
Good point - I'll think about doing this and updating the documentation (since users would need to use python run_phylo_cnv.py versus just run_phylo_cnv.py).

Also, did you run into an error when running run_phylo_cnv.py with the old version of python? If so, what is that version?

**Comment by snayfach** [comment]
Actually, never mind about needing to update the documentation. Users would still be able to use run_phylo_cnv.py

**Comment by mingzhi** [comment]
The default version of python in our HPC is 2.6.6. I never try to run PhyloCNV using this old version of python, since I need to install all the other packages, which I am not sure will be successful or not. And python 2.7 works fine.

**Comment by snayfach** [comment]
I've followed your recommendation and am now using #!/usr/bin/env python
